# Copyright (C) 2023 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

test_suite(
    name = "tests",
    tests = [
        "@gbl//libbootconfig:libbootconfig_test",
        "@gbl//libbootimg:libbootimg_test",
        "@gbl//libefi:libefi_test",
        "@gbl//libfastboot:libfastboot_test",
        "@gbl//libfdt:libfdt_test",
        "@gbl//libgbl:libgbl_test",
        "@gbl//libstorage:libstorage_doc_test",
        "@gbl//libstorage:libstorage_test",
        "@gbl//third_party/libzbi:libzbi_test",
    ],
)
